name: Deploy to GitHub Pages

on:
  push:
    branches: [ "main" ]   # publica al hacer push a main
  workflow_dispatch:        # permite ejecutarlo manualmente

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Sube el sitio tal cual (carpeta raíz del repo)
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .          # cambia a ./docs si publicas desde /docs

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
